# WARNING - Generated by {fusen} from dev/flat_core.Rmd: do not edit by hand

test_that("sort_uniq works", {
  expect_equal(
    object = {
      vec <- sample(1:10, size = 100, replace=TRUE)

      len_uniq(vec)
    },

    expected = 10
  )
})
