# WARNING - Generated by {fusen} from dev/flat_core.Rmd: do not edit by hand

test_that("sort_uniq only returns 10 numbers", {
  expect_equal(
    object = {
      vec <- sample(1:10, size = 100, replace=TRUE)

      sort_uniq(vec)
    },

    expected = 1:10
  )
})
