# WARNING - Generated by {fusen} from dev/flat_core.Rmd: do not edit by hand

#' %!in%
#' 
#' An operator that negates the %in% operator
#' 
#' @param x the thing you want to not find in the table
#' @param table the table you're searching through for this thing
#' @return boolean
#' 
#' @export
#' @examples
#' 1 %!in% 2:10
'%!in%' <- function(x,y)!('%in%'(x,y))
