# WARNING - Generated by {fusen} from dev/flat_core.Rmd: do not edit by hand

#' len_uniq
#' 
#' A short hand for unique() %>% length()
#' 
#' @param vec A vector with a various objects
#' @return The number of unique objects in the vector
#' @export
#'
#' @examples
#' vec <- sample(1:10, size = 20, replace=TRUE)
#'
#' vec
#'
#' sort_uniq(vec)
len_uniq <- function(vec) {
  length(unique(vec))
}
