# WARNING - Generated by {fusen} from dev/flat_core.Rmd: do not edit by hand

#' %!in%
#' 
#' An operator that negates the %in% operator
#' 
#' @return boolean
#' 
#' @export
`%!in%` <- Negate(`%in%`)
