# WARNING - Generated by {fusen} from dev/flat_core.Rmd: do not edit by hand

#' sort_uniq
#' 
#' Description
#' 
#' A Shorthand for unique() %>% sort()
#'
#' @param vec A vector that can be reasonably sorted
#' @return A sorted vector of unique values in the vector
#' @export
#'
#' @examples
#' vec <- sample(1:10, size = 20, replace=TRUE)
#'
#' vec
#'
#' sort_uniq(vec)
sort_uniq <- function(vec) {
  sort(unique(vec))
}
